spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/agora?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: tony267
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true # ddl-auto 실행후 data.sql 실행되도록
  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath:data.sql

#key:
#  token: ygb-server
#  secret: akHBbUbETF
#  id: KUYoWroCpUn72pHUQ5FN
#
#valid-time: 120

#cloud:
#  aws:
#    s3:
#      bucket: "hh-image-storage"
#      folder: "ygb/"
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#    credentials:
#      accessKey: "AKIAYAT4GQMYLMMJSPW2"
#      secretKey: "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"